/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
